permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Frank Chen
  email: 920924960@qq.com
  link: http://qq920924960.blog.163.com/
  weibo: http://weibo.com/qq920924960
  github: https://github.com/QQ920924960
  music: http://qq920924960.blog.163.com/music
  linkedin: https://github.com/QQ920924960

# 站点信息
title: QQ920924960的博客
description: My personal blog
url: http://920924960.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/icon.png
favicon: /public/img/icon.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书
newest: 最新文章

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
